remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
title: My Portfolio
include:
  - assets
  - assets/js/react-init.js
  - assets/js/app.js
  - assets/js/components
